name: Validate with hassfest

on:
  push:
    paths-ignore:
      - "browser_extensions/chrome"
  pull_request:
    paths-ignore:
      - "browser_extensions/chrome"
  schedule:
    - cron:  '0 0 * * *'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - uses: "home-assistant/actions/hassfest@master"
